server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: jwttutorial
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/jwttutorial
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

